spring:
  application:
    name: backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meubanco}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:adminpassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
